# Calma Model Training Configuration

model:
  base_model: "meta-llama/Llama-3.2-3B-Instruct"
  max_length: 512
  
data:
  train_file: "data/raw/training_data.json"
  test_size: 0.2
  
lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.1
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  
training:
  num_epochs: 3
  batch_size: 2
  gradient_accumulation_steps: 8
  learning_rate: 2e-4
  warmup_steps: 100
  weight_decay: 0.01
  
hardware:
  fp16: true
  gradient_checkpointing: true
  dataloader_pin_memory: false